export const DASHBOARD_GET_FETCH = 'DASHBOARD_GET_FETCH';
export const DASHBOARD_GET_SUCCESS = 'DASHBOARD_GET_SUCCESS';
export const DASHBOARD_GET_ERROR = 'DASHBOARD_GET_ERROR';

export const DASHBOARD_CLEAR = 'DASHBOARD_CLEAR';
